services:
  - type: worker
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: DISCORD_TOKEN
        fromSecret: true # RenderのSecretsで設定することを推奨
    port: 0  # ポートスキャンを無効化
