services:
  - type: worker
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m bot
    envVars:
      - key: DISCORD_TOKEN
        fromSecret: true # RenderのSecretsで設定することを推奨
