services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m bot
    envVars:
      - key: DISCORD_TOKEN
        fromSecret: true # RenderのSecretsで設定することを推奨
    healthCheck:
      path: /health
      interval: 30s
      timeout: 5s
      threshold: 3
    port: 8080
